tool_name: BinaryPacketsDSL
author: Magnus Pettersson
version: 0.1.0
program: mop
version: 18414
friendly_name: Mist of Pandaria

IgnoredCases:
  - SMSG_BATTLE_PAY_DISTRIBUTION_UPDATE
  - CMSG_PLAYER_LOGIN
  - SMSG_ENUM_CHARACTERS_RESULT
  - SMSG_AUTH_RESPONSE
  - test
  - SMSG_ADDON_INFO

Logging:
  # Specify the logging levels as names (comma-separated) or use "All" for all levels.
  # Levels:
  #   - None
  #   - Success
  #   - Information
  #   - Anticheat
  #   - Warning
  #   - Error
  #   - Debug
  #   - Script
  #   - All
  # Example:
  #  logging_levels: Information, Success, Debug, Script, Error
  #  logging_levels: All
  logging_levels:  All
  logging_file_leves: All
  log_file: dsl.log
  log_file_unit_test: unit_test.log

  # Define the date format for log timestamps.
  # Examples of formats:
  # usage: date_format: *se
  enGB: &enGB " [%Y-%m-%d %H:%M:%S]"
  en: &en " [%m/%d/%Y %I:%M:%S %p]"
  ru: &ru " [%d.%m.%Y %H:%M:%S]"
  se: &se " [%Y-%m-%d %H:%M:%S]"
  none: &none ""

  date_format: *none